server:
#  address: 192.168.249.60
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/CDL_Test
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: EmployeeService
  mail:
    host: smtp.gmail.com
    port: 587
    username: kvsubbu.db2@gmail.com
    password: qwdvzkkfhycnyeoj
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  



